### ISSUE TITLE
win10使用会导致卡顿

### ISSUE THREAD

**Issue by Polynomia** [cjybyjk/MIUI_Theme_Magiskizer#1]
我在一台win10的机器上使用软件时，读取文件会导致整个电脑卡顿，且显示“桌面无反应”
重现率100%
在一台win7虚拟机中使用无此问题

**Comment by cjybyjk** [comment]
我在win10虚拟机下测试并未发现问题，请问是所有的mtz文件都会出现这个问题吗

**Comment by Polynomia** [comment]
尝试了三个mtz文件均出现这样的问题....因为对windows不熟悉，也不知道该如何排查...

**Comment by cjybyjk** [comment]
是在解包时出的问题吗？请告诉我左下角那个label显示的状态
目前怀疑是因为关闭了跨线程控件访问检查，但是不能确定。下个版本将使用invoke

**Comment by Polynomia** [comment]
不是解析包的时候出现的...是点击添加，然后在文件管理器中浏览出现的卡顿...

**Comment by cjybyjk** [comment]
我使用的是.net framework 提供的OpenfileDialog，正常情况下应该不会出现这种问题。
表示无能为力qwq
